ARG version
FROM almalinux:${version:-8}
#RUN cat /etc/*release = to know the os of the system
ARG COURSE=Docker
ARG TRAINER=Nikhil
ARG Duration=120HRS
ENV Duration=${Duration}
RUN echo "Course is: ${COURSE}, Trainer is: ${TRAINER}, Duration is: ${Duration}"
CMD [ "sleep","100" ]